version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sfi"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-wtgn18yf0tgr"
s3_prefix = "sfi"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
