AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sfi-form-lambda
 
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Api:
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'*"
      AllowOrigin: "'*'"
  Function:
    Timeout: 3

Resources:
  # GetEmployeeForm:
  #   Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
  #   Properties:
  #     CodeUri: rest/
  #     Handler: app.employeeFormHandler
  #     Runtime: nodejs16.x
  #     Architectures:
  #       - x86_64
  #     Events:
  #       HelloWorld:
  #         Type: HttpApi
  #         Properties:
  #           Path: /employeeform
  #           Method: get
  # ApiGatewayApi:
  #   Type: AWS::Serverless::HttpApi
  #   Properties:
  #     StageName: Prod
  #     Cors:
  #       AllowMethods: "'*'"
  #       AllowHeaders: "'*'"
  #       AllowOrigin: "'*'"
  Verify:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: rest/
      Handler: auth.verify
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      Events:
        HelloWorld:
          Type: HttpApi
          Properties:
            Path: /auth/verify
            Method: post

  Login:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: rest/
      Handler: auth.login
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      Events:
        HelloWorld:
          Type: HttpApi
          Properties:
            Path: /auth/login
            Method: post
